START
INPUT NAME
INPUT DATE OF BIRTH
INPUT EMAIL ADDRESS
INPUT PHONE NUMBER
INPUT NUMBER OF SIBLINGD
INNPUT MEDICAL DIAGNOSIS
INPUT VILLAGE RESIDENT
INPUT DATA TYPE WITH FLOAT
COMPUTE DISCOUNT
PRINT 
STOP